name: make-release
on:
  push:
    tags: 
      - 'v*'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with: 
          profile: minimal
          toolchain: stable
      - name: install apt packages
        run: sudo apt-get update && sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libgtk-3-dev
      - name: build
        run: cargo build -r
      - uses: actions/upload-artifact@v1
        with:
          name: linux-binary
          path: target/release/rusty-beads
  build-windows:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with: 
          profile: minimal
          toolchain: stable
      - name: build
        run: cargo build -r
      - uses: actions/upload-artifact@v1
        with:
          name: windows-binary
          path: target/release/rusty-beads.exe

  make-release:
    needs: 
      - build-linux
      - build-windows
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: download linux binaries
        uses: actions/download-artifact@v1
        with:
          name: linux-binary
      - name: download windows binaries
        uses: actions/download-artifact@v1
        with:
          name: windows-binary
      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: linux-binary/rusty-beads
          asset_name: rusty-beads-linux
          asset_content_type: application/octet-stream
      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: windows-binary/rusty-beads.exe
          asset_name: rusty-beads-win.exe
          asset_content_type: application/octet-stream